extensions:
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  hostmetrics:
    default_collection_interval: 60s
    scrapers:
      cpu:
        report_per_cpu: true
      memory:
      disk:
      filesystem:

exporters:
  logging:
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      exporters: [prometheus, logging]

  extensions: [zpages]
